name: Update Ski Status
on:
  schedule:
    - cron: '*/15 * * * *' # S'exécute toutes les 15 minutes
  workflow_dispatch:      # Permet de le lancer à la main pour tester

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install playwright Pillow
          playwright install chromium

      - name: Run Scraper
        run: python scraper.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "SkiBot"
          git config --global user.email "bot@github.com"
          git add status.txt
          git commit -m "Mise à jour statut" || exit 0
          git push
- name: Archive screenshot
        uses: actions/upload-artifact@v4
        with:
          name: view-from-bot
          path: debug_map.png
