name: Update Ski Status

on:
  schedule:
    # Se lance toutes les 15 minutes, entre 8h et 18h (UTC)
    # Note : 7h UTC = 8h ou 9h à Valfréjus selon l'heure d'été/hiver
    - cron: '*/15 7-17 * * *'
  workflow_dispatch: # Permet de le lancer à la main pour tester

permissions:
  contents: write # Autorisation cruciale pour que le robot puisse modifier status.txt

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install playwright Pillow pytz
          playwright install chromium

      - name: Run Scraper Loop
        # On définit une variable d'environnement pour que Git puisse pusher
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scraper.py

      - name: Upload debug screenshot
        # En cas d'erreur, on garde une trace de ce que le robot a vu
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshot
          path: debug_map.png
